version: "3.6"
services:
    bot1:
        image: nsychev/tickets-bot
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - postgres1
        volumes:
            - ./bot.py:/app/bot.py
            - ./tickets/:/app/tickets/
            - ./models/:/app/models/
            - ./config/:/app/config/
        restart: always
        environment:
            - TZ=Europe/Moscow
        networks:
            - bot1_network
    postgres1:
        image: postgres:alpine
        environment:
            POSTGRES_HOST_AUTH_METHOD: trust
        restart: always
        networks:
            - bot1_network

networks:
    bot1_network:
